### ISSUE TITLE
https://anilist-api.readthedocs.io/ doesn't exist

### ISSUE THREAD

**Issue by nicolapreda** [twissell-/anipy#4]
Hi,
i cannot find the docs linked in the readme (https://anilist-api.readthedocs.io/), 
can you help me?

Thanks :D

**Comment by alex-star-gh** [comment]
This is a library for API v1 which was shutdown years ago so the docs are gone and this package won't work anymore.

**Comment by nicolapreda** [comment]
Ok, thanks
